package io.wasted.util.test

import io.wasted.util.PooledResource
import org.scalatest._

class PooledResourceSpec extends WordSpec {
  case class TestMeHard(msg: String)

  val obj = TestMeHard("Default String")
  val pool = new PooledResource(() => obj, 10, 5)

  "Operating on a PooledResource" should {
    "successfully offering our object #1" in {
      pool.release(obj)
    }
    "successfully offering our object #2" in {
      pool.release(obj)
    }
    "successfully offering our object #3" in {
      pool.release(obj)
    }
    "get an object that was generated by us #1" in {
      assert(pool.get() == Some(obj))
    }
    "get an object that was generated by us #2" in {
      assert(pool.get() == Some(obj))
    }
    "get an object that was generated by us #3" in {
      assert(pool.get() == Some(obj))
    }
    "get the default object which gets generated by default" in {
      assert(pool.get() == Some(obj))
    }
  }

}

